% Não mude nada aqui
\chapter*{Anexos}
\addcontentsline{toc}{chapter}{Anexos}
\counterwithout{figure}{chapter}
\counterwithout{table}{chapter}
\renewcommand{\thefigure}{anexo\arabic{figure}}
\renewcommand{\thetable}{anexo\arabic{table}}


% Insira aqui seus Anexos

\section*{Anexo A}

Vestibulum blandit vestibulum porta. Proin scelerisque eros molestie
accumsan ultrices. Sed augue felis, hendrerit ac nibh vitae, aliquet
vehicula massa. Etiam in scelerisque dolor, et interdum mauris. Nulla
facilisis ac ligula a pharetra.

\section*{Anexo B}

Etiam in scelerisque dolor, et interdum mauris.